version: '3.8'

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: java_app_container
    ports:
      - "${APP_PORT:-9090}:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
